/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ChunkExecutorOptions {
  jobName: string
  stepName: string
  chunkSize: number
  skipLimit?: number
  retryLimit?: number
  enableLogging?: boolean
}
/**
 * NAPI에 노출되는 Job 실행 결과 객체
 *
 * JS 쪽에서 `JobLauncher.launch()` 호출 결과로 전달받는 구조체.
 */
export interface JobExecution {
  /** 실행된 Job의 고유 ID (UUID v4) */
  jobExecutionId: string
  /** Job 이름 */
  jobName: string
  /** 최종 상태 문자열 ("COMPLETED", "FAILED", ...) */
  status: string
  /** Job 전체 읽기 수 (모든 Step 합계) */
  readCount: number
  /** Job 전체 처리 수 (모든 Step 합계) */
  processCount: number
  /** Job 전체 쓰기 수 (모든 Step 합계) */
  writeCount: number
  /** Job 전체 건너뛴 수 (모든 Step 합계) */
  skipCount: number
  /** 완료된 Chunk 커밋 수 (모든 Step 합계) */
  commitCount: number
  /** Job 시작 시각 (Unix ms) */
  startTime: number
  /** Job 종료 시각 (Unix ms), 실행 중이면 None */
  endTime?: number
  /** 전체 소요 시간 (ms) */
  durationMs?: number
  /** 종료 메시지 (오류가 있을 경우 오류 원인 포함) */
  exitMessage?: string
  /** 각 Step의 세부 실행 결과 (JSON 직렬화) */
  stepExecutions: Array<string>
}
/** 엔진 버전을 반환한다 (Cargo.toml의 version 필드와 동기화) */
export declare function engineVersion(): string
/** 엔진 빌드 정보를 반환한다 */
export interface EngineBuildInfo {
  /** 엔진 버전 (semver) */
  version: string
  /** Rust 컴파일러 버전 */
  rustVersion: string
  /** 빌드 타겟 트리플 (예: "aarch64-apple-darwin") */
  target: string
  /** 릴리즈 빌드 여부 */
  isRelease: boolean
  /** NAPI-RS 버전 */
  napiVersion: string
}
/**
 * 엔진의 빌드 정보를 반환한다.
 *
 * 디버깅 및 호환성 확인 시 활용한다.
 */
export declare function getBuildInfo(): EngineBuildInfo
/**
 * Rust 엔진이 정상적으로 로드되었는지 확인하는 핑 함수.
 *
 * NestJS 모듈 초기화 시 엔진 바인딩이 제대로 로드되었는지 검증하는 데 사용한다.
 */
export declare function ping(): string
/** 비동기 핑 — Tokio 런타임이 정상 동작하는지 확인한다 */
export declare function pingAsync(): Promise<string>
/**
 * Rust 측 고해상도 타임스탬프 (Unix epoch 기준, 밀리초)
 *
 * JS의 `Date.now()`보다 정밀도가 높은 타임스탬프를 제공한다.
 */
export declare function nowMs(): number
/** 두 타임스탬프 사이의 경과 시간(ms)을 계산한다 */
export declare function elapsedMs(startMs: number): number
export declare class ChunkExecutor {
  constructor(options: ChunkExecutorOptions)
  get jobName(): string
  get stepName(): string
  get chunkSize(): number
  requestStop(): void
  /**
   * Chunk 지향 배치를 실행하고 JS Promise<JobExecution> 을 반환한다.
   *
   * 콜백 규약:
   *   reader_fn    : (offset: number,    reply: (json: string) => void) => void
   *   processor_fn : (itemsJson: string, reply: (json: string) => void) => void
   *   writer_fn    : (itemsJson: string, reply: (json: string) => void) => void
   *
   *   reply 인자는 처리 완료 후 정확히 1회 호출. 오류 시 '__ERROR__:msg'.
   */
  execute(readerFn: (...args: any[]) => any, processorFn: (...args: any[]) => any, writerFn: (...args: any[]) => any): object
}
